//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Passenger
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Universitet;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации PassengerL.
    /// </summary>
    public partial class PassengerLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PassengerLFilterDto"/> class.
        /// </summary>
        public PassengerLFilterDto()
        {
            DtoType = typeof(PassengerLDto);
        }

        /// <summary>
        /// Passport number.
        /// </summary>
        public string? PassportNumber { get; set; }

        /// <summary>
        /// Passport number.
        /// </summary>
        public FilterOperation? PassportNumberOp { get; set; }
        /// <summary>
        /// First name.
        /// </summary>
        public string? FirstName { get; set; }

        /// <summary>
        /// First name.
        /// </summary>
        public FilterOperation? FirstNameOp { get; set; }
        /// <summary>
        /// Last name.
        /// </summary>
        public string? LastName { get; set; }

        /// <summary>
        /// Last name.
        /// </summary>
        public FilterOperation? LastNameOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (PassportNumberOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Passenger>(PassportNumberOp.Value, d => d.PassportNumber, PassportNumber));
            }

            if (FirstNameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Passenger>(FirstNameOp.Value, d => d.FirstName, FirstName));
            }

            if (LastNameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Passenger>(LastNameOp.Value, d => d.LastName, LastName));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
