//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Passenger
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Passenger.PassengerL.
    /// </summary>
    [DataView(typeof(Passenger), "PassengerL")]
    public partial class PassengerLDto : PassengerDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="PassengerLDto"/>.
        /// </summary>
        public PassengerLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="PassengerLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public PassengerLDto(Passenger source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Passport number.
        /// </summary>
        [PropertyName("PassportNumber")]
        [CaptionProperty("Passport number")]
        public string PassportNumber { get; set; } = string.Empty;

                /// <summary>
        /// First name.
        /// </summary>
        [PropertyName("FirstName")]
        [CaptionProperty("First name")]
        public string FirstName { get; set; } = string.Empty;

                /// <summary>
        /// Last name.
        /// </summary>
        [PropertyName("LastName")]
        [CaptionProperty("Last name")]
        public string LastName { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override PassengerLDto FillFromClass(Passenger source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            PassportNumber = source.PassportNumber;
            FirstName = source.FirstName;
            LastName = source.LastName;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Passenger destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.PassportNumber = PassportNumber;
            destination.FirstName = FirstName;
            destination.LastName = LastName;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
