//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Helicopter
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Helicopter.HelicopterL.
    /// </summary>
    [DataView(typeof(Helicopter), "HelicopterL")]
    public partial class HelicopterLDto : HelicopterDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="HelicopterLDto"/>.
        /// </summary>
        public HelicopterLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="HelicopterLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public HelicopterLDto(Helicopter source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Rotor diameter.
        /// </summary>
        [PropertyName("RotorDiameter")]
        [CaptionProperty("Rotor diameter")]
        public double RotorDiameter { get; set; }

        /// <summary>
        /// Max altitude.
        /// </summary>
        [PropertyName("MaxAltitude")]
        [CaptionProperty("Max altitude")]
        public double MaxAltitude { get; set; }

                /// <summary>
        /// Registration number.
        /// </summary>
        [PropertyName("RegistrationNumber")]
        [CaptionProperty("Registration number")]
        public string RegistrationNumber { get; set; } = string.Empty;

                /// <summary>
        /// Model.
        /// </summary>
        [PropertyName("Model")]
        [CaptionProperty("Model")]
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Capacity.
        /// </summary>
        [PropertyName("Capacity")]
        [CaptionProperty("Capacity")]
        public int Capacity { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override HelicopterLDto FillFromClass(Helicopter source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            RotorDiameter = source.RotorDiameter;
            MaxAltitude = source.MaxAltitude;
            RegistrationNumber = source.RegistrationNumber;
            Model = source.Model;
            Capacity = source.Capacity;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Helicopter destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.RotorDiameter = RotorDiameter;
            destination.MaxAltitude = MaxAltitude;
            destination.RegistrationNumber = RegistrationNumber;
            destination.Model = Model;
            destination.Capacity = Capacity;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
