//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.AssosiationClass
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления AssosiationClass.AssosiationClassE.
    /// </summary>
    [DataView(typeof(AssosiationClass), "AssosiationClassE")]
    public partial class AssosiationClassEDto : AssosiationClassDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AssosiationClassEDto"/>.
        /// </summary>
        public AssosiationClassEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AssosiationClassEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AssosiationClassEDto(AssosiationClass source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// AssosiationName.
        /// </summary>
        [PropertyName("AssosiationName")]
        [CaptionProperty("AssosiationName")]
        public string AssosiationName { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AssosiationClassEDto FillFromClass(AssosiationClass source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            AssosiationName = source.AssosiationName;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(AssosiationClass destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.AssosiationName = AssosiationName;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
