//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { HelicopterService } from '@/services/Helicopter.service';

const useDeleteAllHelicopter = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllHelicopter,
    mutateAsync: deleteAllHelicopterAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => HelicopterService.DeleteAllHelicopter(ids),
    onSuccess: (_, ids) => {
      const className = 'helicopter';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllHelicopter, deleteAllHelicopterAsync, isPending };
};

export default useDeleteAllHelicopter;
