//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { HelicopterService } from '@/services/Helicopter.service';

const useDeleteHelicopter = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteHelicopter,
    mutateAsync: deleteHelicopterAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => HelicopterService.DeleteHelicopter(id),
    onSuccess: (_, id) => {
      const className = 'helicopter';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteHelicopter, deleteHelicopterAsync, isPending };
};

export default useDeleteHelicopter;
