//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { InheritanceClassService } from '@/services/InheritanceClass.service';
import { IBaseInheritanceClass } from '@/types/InheritanceClass.types';

const useCreateInheritanceClass = <T extends IBaseInheritanceClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    inheritanceClass: T;
    viewName: string;
  };

  const {
    mutate: createInheritanceClass,
    mutateAsync: createInheritanceClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      InheritanceClassService.CreateInheritanceClass<T>(createRecordArgs.inheritanceClass, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'inheritanceClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createInheritanceClass, createInheritanceClassAsync, isPending };
};

export default useCreateInheritanceClass;
