//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { FlightService } from '@/services/Flight.service';

const useDeleteFlight = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteFlight,
    mutateAsync: deleteFlightAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => FlightService.DeleteFlight(id),
    onSuccess: (_, id) => {
      const className = 'flight';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteFlight, deleteFlightAsync, isPending };
};

export default useDeleteFlight;
