//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAircraft {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAircraft custom)

  // *** End programmer edit section *** (IBaseAircraft custom)
}

export interface IAircraftE extends IBaseAircraft {
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IAircraftE custom)

  // *** End programmer edit section *** (IAircraftE custom)
}

export interface IAircraftL extends IBaseAircraft {
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IAircraftL custom)

  // *** End programmer edit section *** (IAircraftL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
