//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAirplane {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAirplane custom)

  // *** End programmer edit section *** (IBaseAirplane custom)
}

export interface IAirplaneE extends IBaseAirplane {
  wingspan: number;
  engineCount: number;
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IAirplaneE custom)

  // *** End programmer edit section *** (IAirplaneE custom)
}

export interface IAirplaneL extends IBaseAirplane {
  wingspan: number;
  engineCount: number;
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IAirplaneL custom)

  // *** End programmer edit section *** (IAirplaneL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
