//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAirport {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAirport custom)

  // *** End programmer edit section *** (IBaseAirport custom)
}

export interface IAirportE extends IBaseAirport {
  code: string;
  name: string;
  // *** Start programmer edit section *** (IAirportE custom)

  // *** End programmer edit section *** (IAirportE custom)
}

export interface IAirportL extends IBaseAirport {
  code: string;
  name: string;
  // *** Start programmer edit section *** (IAirportL custom)

  // *** End programmer edit section *** (IAirportL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
