//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseClass {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseClass custom)

  // *** End programmer edit section *** (IBaseClass custom)
}

export interface IClassE extends IBaseClass {
  address: string;
  name: string;
  assosiationClassId: NonEmptyString;
  // *** Start programmer edit section *** (IClassE custom)

  // *** End programmer edit section *** (IClassE custom)
}

export interface IClassL extends IBaseClass {
  address: string;
  name: string;
  // *** Start programmer edit section *** (IClassL custom)

  // *** End programmer edit section *** (IClassL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
