//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tFlightStatus } from '../enums/tFlightStatus.types';
import { ITicketE as ITicketTicketE } from './Ticket.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseFlight {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseFlight custom)

  // *** End programmer edit section *** (IBaseFlight custom)
}

export interface IFlightE extends IBaseFlight {
  flightNumber: string;
  departureTime: Date | null;
  arrivalTime: Date | null;
  status: tFlightStatus;
  aircraftId: NonEmptyString;
  departureAirportId: NonEmptyString;
  ticket: ITicketTicketE[];
  // *** Start programmer edit section *** (IFlightE custom)

  // *** End programmer edit section *** (IFlightE custom)
}

export interface IFlightL extends IBaseFlight {
  flightNumber: string;
  departureTime: Date | null;
  arrivalTime: Date | null;
  status: tFlightStatus;
  // *** Start programmer edit section *** (IFlightL custom)

  // *** End programmer edit section *** (IFlightL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
