//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseHelicopter {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseHelicopter custom)

  // *** End programmer edit section *** (IBaseHelicopter custom)
}

export interface IHelicopterE extends IBaseHelicopter {
  rotorDiameter: number;
  maxAltitude: number;
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IHelicopterE custom)

  // *** End programmer edit section *** (IHelicopterE custom)
}

export interface IHelicopterL extends IBaseHelicopter {
  rotorDiameter: number;
  maxAltitude: number;
  registrationNumber: string;
  model: string;
  capacity: number;
  // *** Start programmer edit section *** (IHelicopterL custom)

  // *** End programmer edit section *** (IHelicopterL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
