//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseInheritanceClass {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseInheritanceClass custom)

  // *** End programmer edit section *** (IBaseInheritanceClass custom)
}

export interface IInheritanceClassE extends IBaseInheritanceClass {
  name: string;
  address: string;
  inheritance: string;
  // *** Start programmer edit section *** (IInheritanceClassE custom)

  // *** End programmer edit section *** (IInheritanceClassE custom)
}

export interface IInheritanceClassL extends IBaseInheritanceClass {
  address: string;
  inheritance: string;
  name: string;
  // *** Start programmer edit section *** (IInheritanceClassL custom)

  // *** End programmer edit section *** (IInheritanceClassL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
