//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBasePassenger {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBasePassenger custom)

  // *** End programmer edit section *** (IBasePassenger custom)
}

export interface IPassengerE extends IBasePassenger {
  passportNumber: string;
  firstName: string;
  lastName: string;
  // *** Start programmer edit section *** (IPassengerE custom)

  // *** End programmer edit section *** (IPassengerE custom)
}

export interface IPassengerL extends IBasePassenger {
  passportNumber: string;
  firstName: string;
  lastName: string;
  // *** Start programmer edit section *** (IPassengerL custom)

  // *** End programmer edit section *** (IPassengerL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
