//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseTicket {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseTicket custom)

  // *** End programmer edit section *** (IBaseTicket custom)
}

export interface ITicketE extends IBaseTicket {
  ticketNumber: string;
  seatNumber: string;
  price: number;
  passengerId: NonEmptyString;
  // *** Start programmer edit section *** (ITicketE custom)

  // *** End programmer edit section *** (ITicketE custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
