//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AirportService } from '@/services/Airport.service';

const useDeleteAirport = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAirport,
    mutateAsync: deleteAirportAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => AirportService.DeleteAirport(id),
    onSuccess: (_, id) => {
      const className = 'airport';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteAirport, deleteAirportAsync, isPending };
};

export default useDeleteAirport;
