//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Aircraft.
    /// </summary>
    // *** Start programmer edit section *** (Aircraft CustomAttributes)

    // *** End programmer edit section *** (Aircraft CustomAttributes)
    [AutoAltered()]
    [Caption("Aircraft")]
    [View("AircraftE", new string[] {
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    [View("AircraftL", new string[] {
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    public class Aircraft : ICSSoft.STORMNET.DataObject
    {

        private int fCapacity;

        private int fffff;

        private string fModel;

        private string fRegistrationNumber;

        // *** Start programmer edit section *** (Aircraft CustomMembers)

        // *** End programmer edit section *** (Aircraft CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Aircraft.Capacity CustomAttributes)

        // *** End programmer edit section *** (Aircraft.Capacity CustomAttributes)
        public virtual int Capacity
        {
            get
            {
                // *** Start programmer edit section *** (Aircraft.Capacity Get start)

                // *** End programmer edit section *** (Aircraft.Capacity Get start)
                int result = this.fCapacity;
                // *** Start programmer edit section *** (Aircraft.Capacity Get end)

                // *** End programmer edit section *** (Aircraft.Capacity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Aircraft.Capacity Set start)

                // *** End programmer edit section *** (Aircraft.Capacity Set start)
                this.fCapacity = value;
                // *** Start programmer edit section *** (Aircraft.Capacity Set end)

                // *** End programmer edit section *** (Aircraft.Capacity Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Aircraft.ffff CustomAttributes)

        // *** End programmer edit section *** (Aircraft.ffff CustomAttributes)
        public virtual int ffff
        {
            get
            {
                // *** Start programmer edit section *** (Aircraft.ffff Get start)

                // *** End programmer edit section *** (Aircraft.ffff Get start)
                int result = this.fffff;
                // *** Start programmer edit section *** (Aircraft.ffff Get end)

                // *** End programmer edit section *** (Aircraft.ffff Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Aircraft.ffff Set start)

                // *** End programmer edit section *** (Aircraft.ffff Set start)
                this.fffff = value;
                // *** Start programmer edit section *** (Aircraft.ffff Set end)

                // *** End programmer edit section *** (Aircraft.ffff Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Aircraft.Model CustomAttributes)

        // *** End programmer edit section *** (Aircraft.Model CustomAttributes)
        public virtual string Model
        {
            get
            {
                // *** Start programmer edit section *** (Aircraft.Model Get start)

                // *** End programmer edit section *** (Aircraft.Model Get start)
                string result = this.fModel;
                // *** Start programmer edit section *** (Aircraft.Model Get end)

                // *** End programmer edit section *** (Aircraft.Model Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Aircraft.Model Set start)

                // *** End programmer edit section *** (Aircraft.Model Set start)
                this.fModel = value;
                // *** Start programmer edit section *** (Aircraft.Model Set end)

                // *** End programmer edit section *** (Aircraft.Model Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Aircraft.RegistrationNumber CustomAttributes)

        // *** End programmer edit section *** (Aircraft.RegistrationNumber CustomAttributes)
        public virtual string RegistrationNumber
        {
            get
            {
                // *** Start programmer edit section *** (Aircraft.RegistrationNumber Get start)

                // *** End programmer edit section *** (Aircraft.RegistrationNumber Get start)
                string result = this.fRegistrationNumber;
                // *** Start programmer edit section *** (Aircraft.RegistrationNumber Get end)

                // *** End programmer edit section *** (Aircraft.RegistrationNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Aircraft.RegistrationNumber Set start)

                // *** End programmer edit section *** (Aircraft.RegistrationNumber Set start)
                this.fRegistrationNumber = value;
                // *** Start programmer edit section *** (Aircraft.RegistrationNumber Set end)

                // *** End programmer edit section *** (Aircraft.RegistrationNumber Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AircraftE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AircraftE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AircraftE", typeof(Universitet.Aircraft));
                }
            }

            /// <summary>
            /// "AircraftL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AircraftL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AircraftL", typeof(Universitet.Aircraft));
                }
            }
        }

    }
}
