//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Airplane.
    /// </summary>
    // *** Start programmer edit section *** (Airplane CustomAttributes)

    // *** End programmer edit section *** (Airplane CustomAttributes)
    [AutoAltered()]
    [Caption("Airplane")]
    [View("AirplaneE", new string[] {
            "Wingspan as \'Wingspan\'",
            "EngineCount as \'Engine count\'",
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    [View("AirplaneL", new string[] {
            "Wingspan as \'Wingspan\'",
            "EngineCount as \'Engine count\'",
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    public class Airplane : ICSSoft.STORMNET.DataObject
    {

        private int fCapacity;

        private int fEngineCount;

        private int fffff;

        private string fModel;

        private string fRegistrationNumber;

        private double fWingspan;

        // *** Start programmer edit section *** (Airplane CustomMembers)

        // *** End programmer edit section *** (Airplane CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.Capacity CustomAttributes)

        // *** End programmer edit section *** (Airplane.Capacity CustomAttributes)
        public virtual int Capacity
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.Capacity Get start)

                // *** End programmer edit section *** (Airplane.Capacity Get start)
                int result = this.fCapacity;
                // *** Start programmer edit section *** (Airplane.Capacity Get end)

                // *** End programmer edit section *** (Airplane.Capacity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.Capacity Set start)

                // *** End programmer edit section *** (Airplane.Capacity Set start)
                this.fCapacity = value;
                // *** Start programmer edit section *** (Airplane.Capacity Set end)

                // *** End programmer edit section *** (Airplane.Capacity Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.EngineCount CustomAttributes)

        // *** End programmer edit section *** (Airplane.EngineCount CustomAttributes)
        public virtual int EngineCount
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.EngineCount Get start)

                // *** End programmer edit section *** (Airplane.EngineCount Get start)
                int result = this.fEngineCount;
                // *** Start programmer edit section *** (Airplane.EngineCount Get end)

                // *** End programmer edit section *** (Airplane.EngineCount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.EngineCount Set start)

                // *** End programmer edit section *** (Airplane.EngineCount Set start)
                this.fEngineCount = value;
                // *** Start programmer edit section *** (Airplane.EngineCount Set end)

                // *** End programmer edit section *** (Airplane.EngineCount Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.ffff CustomAttributes)

        // *** End programmer edit section *** (Airplane.ffff CustomAttributes)
        public virtual int ffff
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.ffff Get start)

                // *** End programmer edit section *** (Airplane.ffff Get start)
                int result = this.fffff;
                // *** Start programmer edit section *** (Airplane.ffff Get end)

                // *** End programmer edit section *** (Airplane.ffff Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.ffff Set start)

                // *** End programmer edit section *** (Airplane.ffff Set start)
                this.fffff = value;
                // *** Start programmer edit section *** (Airplane.ffff Set end)

                // *** End programmer edit section *** (Airplane.ffff Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.Model CustomAttributes)

        // *** End programmer edit section *** (Airplane.Model CustomAttributes)
        public virtual string Model
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.Model Get start)

                // *** End programmer edit section *** (Airplane.Model Get start)
                string result = this.fModel;
                // *** Start programmer edit section *** (Airplane.Model Get end)

                // *** End programmer edit section *** (Airplane.Model Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.Model Set start)

                // *** End programmer edit section *** (Airplane.Model Set start)
                this.fModel = value;
                // *** Start programmer edit section *** (Airplane.Model Set end)

                // *** End programmer edit section *** (Airplane.Model Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.RegistrationNumber CustomAttributes)

        // *** End programmer edit section *** (Airplane.RegistrationNumber CustomAttributes)
        public virtual string RegistrationNumber
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.RegistrationNumber Get start)

                // *** End programmer edit section *** (Airplane.RegistrationNumber Get start)
                string result = this.fRegistrationNumber;
                // *** Start programmer edit section *** (Airplane.RegistrationNumber Get end)

                // *** End programmer edit section *** (Airplane.RegistrationNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.RegistrationNumber Set start)

                // *** End programmer edit section *** (Airplane.RegistrationNumber Set start)
                this.fRegistrationNumber = value;
                // *** Start programmer edit section *** (Airplane.RegistrationNumber Set end)

                // *** End programmer edit section *** (Airplane.RegistrationNumber Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airplane.Wingspan CustomAttributes)

        // *** End programmer edit section *** (Airplane.Wingspan CustomAttributes)
        public virtual double Wingspan
        {
            get
            {
                // *** Start programmer edit section *** (Airplane.Wingspan Get start)

                // *** End programmer edit section *** (Airplane.Wingspan Get start)
                double result = this.fWingspan;
                // *** Start programmer edit section *** (Airplane.Wingspan Get end)

                // *** End programmer edit section *** (Airplane.Wingspan Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airplane.Wingspan Set start)

                // *** End programmer edit section *** (Airplane.Wingspan Set start)
                this.fWingspan = value;
                // *** Start programmer edit section *** (Airplane.Wingspan Set end)

                // *** End programmer edit section *** (Airplane.Wingspan Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AirplaneE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AirplaneE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AirplaneE", typeof(Universitet.Airplane));
                }
            }

            /// <summary>
            /// "AirplaneL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AirplaneL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AirplaneL", typeof(Universitet.Airplane));
                }
            }
        }

    }
}
