//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Airport.
    /// </summary>
    // *** Start programmer edit section *** (Airport CustomAttributes)

    // *** End programmer edit section *** (Airport CustomAttributes)
    [AutoAltered()]
    [Caption("Airport")]
    [View("AirportE", new string[] {
            "Code as \'Code\'",
            "Name as \'Name\'"})]
    [View("AirportL", new string[] {
            "Code as \'Code\'",
            "Name as \'Name\'"})]
    public class Airport : ICSSoft.STORMNET.DataObject
    {

        private string fCode;

        private string fName;

        // *** Start programmer edit section *** (Airport CustomMembers)

        // *** End programmer edit section *** (Airport CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airport.Code CustomAttributes)

        // *** End programmer edit section *** (Airport.Code CustomAttributes)
        public virtual string Code
        {
            get
            {
                // *** Start programmer edit section *** (Airport.Code Get start)

                // *** End programmer edit section *** (Airport.Code Get start)
                string result = this.fCode;
                // *** Start programmer edit section *** (Airport.Code Get end)

                // *** End programmer edit section *** (Airport.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airport.Code Set start)

                // *** End programmer edit section *** (Airport.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (Airport.Code Set end)

                // *** End programmer edit section *** (Airport.Code Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Airport.Name CustomAttributes)

        // *** End programmer edit section *** (Airport.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Airport.Name Get start)

                // *** End programmer edit section *** (Airport.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Airport.Name Get end)

                // *** End programmer edit section *** (Airport.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Airport.Name Set start)

                // *** End programmer edit section *** (Airport.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Airport.Name Set end)

                // *** End programmer edit section *** (Airport.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AirportE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AirportE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AirportE", typeof(Universitet.Airport));
                }
            }

            /// <summary>
            /// "AirportL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AirportL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AirportL", typeof(Universitet.Airport));
                }
            }
        }

    }
}
