//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Flight.
    /// </summary>
    // *** Start programmer edit section *** (Flight CustomAttributes)

    // *** End programmer edit section *** (Flight CustomAttributes)
    [AutoAltered()]
    [Caption("Flight")]
    [View("FlightE", new string[] {
            "FlightNumber as \'Flight number\'",
            "DepartureTime as \'Departure time\'",
            "ArrivalTime as \'Arrival time\'",
            "Status as \'Status\'",
            "Aircraft as \'Aircraft\'",
            "Aircraft.RegistrationNumber",
            "DepartureAirport as \'DepartureAirport\'",
            "DepartureAirport.Code"}, Hidden=new string[] {
            "Aircraft.RegistrationNumber",
            "DepartureAirport.Code"})]
    [AssociatedDetailViewAttribute("FlightE", "Ticket", "TicketE", true, "", "Ticket", true, new string[] {
            ""})]
    [View("FlightL", new string[] {
            "FlightNumber as \'Flight number\'",
            "DepartureTime as \'Departure time\'",
            "ArrivalTime as \'Arrival time\'",
            "Status as \'Status\'"}, Hidden=new string[] {
            "Aircraft.RegistrationNumber",
            "DepartureAirport.Code"})]
    public class Flight : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fArrivalTime;

        private System.DateTime fDepartureTime;

        private string fFlightNumber;

        private tFlightStatus fStatus;

        private Universitet.Aircraft fAircraft;

        private Universitet.Airport fDepartureAirport;

        private Universitet.DetailArrayOfTicket fTicket;

        // *** Start programmer edit section *** (Flight CustomMembers)

        // *** End programmer edit section *** (Flight CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.ArrivalTime CustomAttributes)

        // *** End programmer edit section *** (Flight.ArrivalTime CustomAttributes)
        public virtual System.DateTime ArrivalTime
        {
            get
            {
                // *** Start programmer edit section *** (Flight.ArrivalTime Get start)

                // *** End programmer edit section *** (Flight.ArrivalTime Get start)
                System.DateTime result = this.fArrivalTime;
                // *** Start programmer edit section *** (Flight.ArrivalTime Get end)

                // *** End programmer edit section *** (Flight.ArrivalTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.ArrivalTime Set start)

                // *** End programmer edit section *** (Flight.ArrivalTime Set start)
                this.fArrivalTime = value;
                // *** Start programmer edit section *** (Flight.ArrivalTime Set end)

                // *** End programmer edit section *** (Flight.ArrivalTime Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.DepartureTime CustomAttributes)

        // *** End programmer edit section *** (Flight.DepartureTime CustomAttributes)
        public virtual System.DateTime DepartureTime
        {
            get
            {
                // *** Start programmer edit section *** (Flight.DepartureTime Get start)

                // *** End programmer edit section *** (Flight.DepartureTime Get start)
                System.DateTime result = this.fDepartureTime;
                // *** Start programmer edit section *** (Flight.DepartureTime Get end)

                // *** End programmer edit section *** (Flight.DepartureTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.DepartureTime Set start)

                // *** End programmer edit section *** (Flight.DepartureTime Set start)
                this.fDepartureTime = value;
                // *** Start programmer edit section *** (Flight.DepartureTime Set end)

                // *** End programmer edit section *** (Flight.DepartureTime Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.FlightNumber CustomAttributes)

        // *** End programmer edit section *** (Flight.FlightNumber CustomAttributes)
        public virtual string FlightNumber
        {
            get
            {
                // *** Start programmer edit section *** (Flight.FlightNumber Get start)

                // *** End programmer edit section *** (Flight.FlightNumber Get start)
                string result = this.fFlightNumber;
                // *** Start programmer edit section *** (Flight.FlightNumber Get end)

                // *** End programmer edit section *** (Flight.FlightNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.FlightNumber Set start)

                // *** End programmer edit section *** (Flight.FlightNumber Set start)
                this.fFlightNumber = value;
                // *** Start programmer edit section *** (Flight.FlightNumber Set end)

                // *** End programmer edit section *** (Flight.FlightNumber Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.Status CustomAttributes)

        // *** End programmer edit section *** (Flight.Status CustomAttributes)
        public virtual tFlightStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Flight.Status Get start)

                // *** End programmer edit section *** (Flight.Status Get start)
                tFlightStatus result = this.fStatus;
                // *** Start programmer edit section *** (Flight.Status Get end)

                // *** End programmer edit section *** (Flight.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.Status Set start)

                // *** End programmer edit section *** (Flight.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Flight.Status Set end)

                // *** End programmer edit section *** (Flight.Status Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.Aircraft CustomAttributes)

        // *** End programmer edit section *** (Flight.Aircraft CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Aircraft"})]
        public virtual Universitet.Aircraft Aircraft
        {
            get
            {
                // *** Start programmer edit section *** (Flight.Aircraft Get start)

                // *** End programmer edit section *** (Flight.Aircraft Get start)
                Universitet.Aircraft result = this.fAircraft;
                // *** Start programmer edit section *** (Flight.Aircraft Get end)

                // *** End programmer edit section *** (Flight.Aircraft Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.Aircraft Set start)

                // *** End programmer edit section *** (Flight.Aircraft Set start)
                this.fAircraft = value;
                // *** Start programmer edit section *** (Flight.Aircraft Set end)

                // *** End programmer edit section *** (Flight.Aircraft Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.DepartureAirport CustomAttributes)

        // *** End programmer edit section *** (Flight.DepartureAirport CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "DepartureAirport"})]
        public virtual Universitet.Airport DepartureAirport
        {
            get
            {
                // *** Start programmer edit section *** (Flight.DepartureAirport Get start)

                // *** End programmer edit section *** (Flight.DepartureAirport Get start)
                Universitet.Airport result = this.fDepartureAirport;
                // *** Start programmer edit section *** (Flight.DepartureAirport Get end)

                // *** End programmer edit section *** (Flight.DepartureAirport Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.DepartureAirport Set start)

                // *** End programmer edit section *** (Flight.DepartureAirport Set start)
                this.fDepartureAirport = value;
                // *** Start programmer edit section *** (Flight.DepartureAirport Set end)

                // *** End programmer edit section *** (Flight.DepartureAirport Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Flight.Ticket CustomAttributes)

        // *** End programmer edit section *** (Flight.Ticket CustomAttributes)
        [PropertyStorage(new string[] {
                "Flight"})]
        public virtual Universitet.DetailArrayOfTicket Ticket
        {
            get
            {
                // *** Start programmer edit section *** (Flight.Ticket Get start)

                // *** End programmer edit section *** (Flight.Ticket Get start)
                if ((this.fTicket == null))
                {
                    this.fTicket = new Universitet.DetailArrayOfTicket(this);
                }
                Universitet.DetailArrayOfTicket result = this.fTicket;
                // *** Start programmer edit section *** (Flight.Ticket Get end)

                // *** End programmer edit section *** (Flight.Ticket Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Flight.Ticket Set start)

                // *** End programmer edit section *** (Flight.Ticket Set start)
                this.fTicket = value;
                // *** Start programmer edit section *** (Flight.Ticket Set end)

                // *** End programmer edit section *** (Flight.Ticket Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "FlightE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FlightE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FlightE", typeof(Universitet.Flight));
                }
            }

            /// <summary>
            /// "FlightL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FlightL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FlightL", typeof(Universitet.Flight));
                }
            }
        }

    }
}
