//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Helicopter.
    /// </summary>
    // *** Start programmer edit section *** (Helicopter CustomAttributes)

    // *** End programmer edit section *** (Helicopter CustomAttributes)
    [AutoAltered()]
    [Caption("Helicopter")]
    [View("HelicopterE", new string[] {
            "RotorDiameter as \'Rotor diameter\'",
            "MaxAltitude as \'Max altitude\'",
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    [View("HelicopterL", new string[] {
            "RotorDiameter as \'Rotor diameter\'",
            "MaxAltitude as \'Max altitude\'",
            "RegistrationNumber as \'Registration number\'",
            "Model as \'Model\'",
            "Capacity as \'Capacity\'"})]
    public class Helicopter : ICSSoft.STORMNET.DataObject
    {

        private int fCapacity;

        private int fffff;

        private double fMaxAltitude;

        private string fModel;

        private string fRegistrationNumber;

        private double fRotorDiameter;

        // *** Start programmer edit section *** (Helicopter CustomMembers)

        // *** End programmer edit section *** (Helicopter CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.Capacity CustomAttributes)

        // *** End programmer edit section *** (Helicopter.Capacity CustomAttributes)
        public virtual int Capacity
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.Capacity Get start)

                // *** End programmer edit section *** (Helicopter.Capacity Get start)
                int result = this.fCapacity;
                // *** Start programmer edit section *** (Helicopter.Capacity Get end)

                // *** End programmer edit section *** (Helicopter.Capacity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.Capacity Set start)

                // *** End programmer edit section *** (Helicopter.Capacity Set start)
                this.fCapacity = value;
                // *** Start programmer edit section *** (Helicopter.Capacity Set end)

                // *** End programmer edit section *** (Helicopter.Capacity Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.ffff CustomAttributes)

        // *** End programmer edit section *** (Helicopter.ffff CustomAttributes)
        public virtual int ffff
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.ffff Get start)

                // *** End programmer edit section *** (Helicopter.ffff Get start)
                int result = this.fffff;
                // *** Start programmer edit section *** (Helicopter.ffff Get end)

                // *** End programmer edit section *** (Helicopter.ffff Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.ffff Set start)

                // *** End programmer edit section *** (Helicopter.ffff Set start)
                this.fffff = value;
                // *** Start programmer edit section *** (Helicopter.ffff Set end)

                // *** End programmer edit section *** (Helicopter.ffff Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.MaxAltitude CustomAttributes)

        // *** End programmer edit section *** (Helicopter.MaxAltitude CustomAttributes)
        public virtual double MaxAltitude
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.MaxAltitude Get start)

                // *** End programmer edit section *** (Helicopter.MaxAltitude Get start)
                double result = this.fMaxAltitude;
                // *** Start programmer edit section *** (Helicopter.MaxAltitude Get end)

                // *** End programmer edit section *** (Helicopter.MaxAltitude Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.MaxAltitude Set start)

                // *** End programmer edit section *** (Helicopter.MaxAltitude Set start)
                this.fMaxAltitude = value;
                // *** Start programmer edit section *** (Helicopter.MaxAltitude Set end)

                // *** End programmer edit section *** (Helicopter.MaxAltitude Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.Model CustomAttributes)

        // *** End programmer edit section *** (Helicopter.Model CustomAttributes)
        public virtual string Model
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.Model Get start)

                // *** End programmer edit section *** (Helicopter.Model Get start)
                string result = this.fModel;
                // *** Start programmer edit section *** (Helicopter.Model Get end)

                // *** End programmer edit section *** (Helicopter.Model Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.Model Set start)

                // *** End programmer edit section *** (Helicopter.Model Set start)
                this.fModel = value;
                // *** Start programmer edit section *** (Helicopter.Model Set end)

                // *** End programmer edit section *** (Helicopter.Model Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.RegistrationNumber CustomAttributes)

        // *** End programmer edit section *** (Helicopter.RegistrationNumber CustomAttributes)
        public virtual string RegistrationNumber
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.RegistrationNumber Get start)

                // *** End programmer edit section *** (Helicopter.RegistrationNumber Get start)
                string result = this.fRegistrationNumber;
                // *** Start programmer edit section *** (Helicopter.RegistrationNumber Get end)

                // *** End programmer edit section *** (Helicopter.RegistrationNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.RegistrationNumber Set start)

                // *** End programmer edit section *** (Helicopter.RegistrationNumber Set start)
                this.fRegistrationNumber = value;
                // *** Start programmer edit section *** (Helicopter.RegistrationNumber Set end)

                // *** End programmer edit section *** (Helicopter.RegistrationNumber Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Helicopter.RotorDiameter CustomAttributes)

        // *** End programmer edit section *** (Helicopter.RotorDiameter CustomAttributes)
        public virtual double RotorDiameter
        {
            get
            {
                // *** Start programmer edit section *** (Helicopter.RotorDiameter Get start)

                // *** End programmer edit section *** (Helicopter.RotorDiameter Get start)
                double result = this.fRotorDiameter;
                // *** Start programmer edit section *** (Helicopter.RotorDiameter Get end)

                // *** End programmer edit section *** (Helicopter.RotorDiameter Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Helicopter.RotorDiameter Set start)

                // *** End programmer edit section *** (Helicopter.RotorDiameter Set start)
                this.fRotorDiameter = value;
                // *** Start programmer edit section *** (Helicopter.RotorDiameter Set end)

                // *** End programmer edit section *** (Helicopter.RotorDiameter Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "HelicopterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HelicopterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HelicopterE", typeof(Universitet.Helicopter));
                }
            }

            /// <summary>
            /// "HelicopterL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HelicopterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HelicopterL", typeof(Universitet.Helicopter));
                }
            }
        }

    }
}
