//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Passenger.
    /// </summary>
    // *** Start programmer edit section *** (Passenger CustomAttributes)

    // *** End programmer edit section *** (Passenger CustomAttributes)
    [AutoAltered()]
    [Caption("Passenger")]
    [View("PassengerE", new string[] {
            "PassportNumber as \'Passport number\'",
            "FirstName as \'First name\'",
            "LastName as \'Last name\'"})]
    [View("PassengerL", new string[] {
            "PassportNumber as \'Passport number\'",
            "FirstName as \'First name\'",
            "LastName as \'Last name\'"})]
    public class Passenger : ICSSoft.STORMNET.DataObject
    {

        private string fFirstName;

        private string fLastName;

        private string fPassportNumber;

        // *** Start programmer edit section *** (Passenger CustomMembers)

        // *** End programmer edit section *** (Passenger CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Passenger.FirstName CustomAttributes)

        // *** End programmer edit section *** (Passenger.FirstName CustomAttributes)
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Passenger.FirstName Get start)

                // *** End programmer edit section *** (Passenger.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Passenger.FirstName Get end)

                // *** End programmer edit section *** (Passenger.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Passenger.FirstName Set start)

                // *** End programmer edit section *** (Passenger.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Passenger.FirstName Set end)

                // *** End programmer edit section *** (Passenger.FirstName Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Passenger.LastName CustomAttributes)

        // *** End programmer edit section *** (Passenger.LastName CustomAttributes)
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Passenger.LastName Get start)

                // *** End programmer edit section *** (Passenger.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Passenger.LastName Get end)

                // *** End programmer edit section *** (Passenger.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Passenger.LastName Set start)

                // *** End programmer edit section *** (Passenger.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Passenger.LastName Set end)

                // *** End programmer edit section *** (Passenger.LastName Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Passenger.PassportNumber CustomAttributes)

        // *** End programmer edit section *** (Passenger.PassportNumber CustomAttributes)
        public virtual string PassportNumber
        {
            get
            {
                // *** Start programmer edit section *** (Passenger.PassportNumber Get start)

                // *** End programmer edit section *** (Passenger.PassportNumber Get start)
                string result = this.fPassportNumber;
                // *** Start programmer edit section *** (Passenger.PassportNumber Get end)

                // *** End programmer edit section *** (Passenger.PassportNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Passenger.PassportNumber Set start)

                // *** End programmer edit section *** (Passenger.PassportNumber Set start)
                this.fPassportNumber = value;
                // *** Start programmer edit section *** (Passenger.PassportNumber Set end)

                // *** End programmer edit section *** (Passenger.PassportNumber Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "PassengerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PassengerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PassengerE", typeof(Universitet.Passenger));
                }
            }

            /// <summary>
            /// "PassengerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PassengerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PassengerL", typeof(Universitet.Passenger));
                }
            }
        }

    }
}
