//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System.ComponentModel;
    using System.Text.Json.Serialization;
    using ICSSoft.STORMNET;

    /// <summary>
    /// T flight status.
    /// </summary>
    [TypeConverter(typeof(CaptionEnumConverter))]
    [JsonConverter(typeof(JsonCaptionEnumConverterFactory))]
    public enum tFlightStatus
    {

        [Caption("")]
        ARRIVED,

        [Caption("")]
        BOARDING,

        [Caption("")]
        CANCELLED,

        [Caption("")]
        DELAYED,

        [Caption("")]
        DEPARTED,

        [Caption("")]
        DIVERTED,

        [Caption("")]
        IN_AIR,

        [Caption("")]
        LANDED,

        [Caption("")]
        SCHEDULED,
    }
}
