//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universitet
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Ticket.
    /// </summary>
    // *** Start programmer edit section *** (Ticket CustomAttributes)

    // *** End programmer edit section *** (Ticket CustomAttributes)
    [AutoAltered()]
    [Caption("Ticket")]
    [View("TicketE", new string[] {
            "TicketNumber as \'Ticket number\'",
            "SeatNumber as \'Seat number\'",
            "Price as \'Price\'",
            "Passenger as \'Passenger\'",
            "Passenger.PassportNumber as \'Passport number\'"}, Hidden=new string[] {
            "Passenger.PassportNumber"})]
    public class Ticket : ICSSoft.STORMNET.DataObject
    {

        private double fPrice;

        private string fSeatNumber;

        private string fTicketNumber;

        private Universitet.Flight fFlight;

        private Universitet.Passenger fPassenger;

        // *** Start programmer edit section *** (Ticket CustomMembers)

        // *** End programmer edit section *** (Ticket CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Ticket.Price CustomAttributes)

        // *** End programmer edit section *** (Ticket.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (Ticket.Price Get start)

                // *** End programmer edit section *** (Ticket.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (Ticket.Price Get end)

                // *** End programmer edit section *** (Ticket.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ticket.Price Set start)

                // *** End programmer edit section *** (Ticket.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (Ticket.Price Set end)

                // *** End programmer edit section *** (Ticket.Price Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Ticket.SeatNumber CustomAttributes)

        // *** End programmer edit section *** (Ticket.SeatNumber CustomAttributes)
        public virtual string SeatNumber
        {
            get
            {
                // *** Start programmer edit section *** (Ticket.SeatNumber Get start)

                // *** End programmer edit section *** (Ticket.SeatNumber Get start)
                string result = this.fSeatNumber;
                // *** Start programmer edit section *** (Ticket.SeatNumber Get end)

                // *** End programmer edit section *** (Ticket.SeatNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ticket.SeatNumber Set start)

                // *** End programmer edit section *** (Ticket.SeatNumber Set start)
                this.fSeatNumber = value;
                // *** Start programmer edit section *** (Ticket.SeatNumber Set end)

                // *** End programmer edit section *** (Ticket.SeatNumber Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Ticket.TicketNumber CustomAttributes)

        // *** End programmer edit section *** (Ticket.TicketNumber CustomAttributes)
        public virtual string TicketNumber
        {
            get
            {
                // *** Start programmer edit section *** (Ticket.TicketNumber Get start)

                // *** End programmer edit section *** (Ticket.TicketNumber Get start)
                string result = this.fTicketNumber;
                // *** Start programmer edit section *** (Ticket.TicketNumber Get end)

                // *** End programmer edit section *** (Ticket.TicketNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ticket.TicketNumber Set start)

                // *** End programmer edit section *** (Ticket.TicketNumber Set start)
                this.fTicketNumber = value;
                // *** Start programmer edit section *** (Ticket.TicketNumber Set end)

                // *** End programmer edit section *** (Ticket.TicketNumber Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Ticket.Flight CustomAttributes)

        // *** End programmer edit section *** (Ticket.Flight CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Flight"})]
        public virtual Universitet.Flight Flight
        {
            get
            {
                // *** Start programmer edit section *** (Ticket.Flight Get start)

                // *** End programmer edit section *** (Ticket.Flight Get start)
                Universitet.Flight result = this.fFlight;
                // *** Start programmer edit section *** (Ticket.Flight Get end)

                // *** End programmer edit section *** (Ticket.Flight Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ticket.Flight Set start)

                // *** End programmer edit section *** (Ticket.Flight Set start)
                this.fFlight = value;
                // *** Start programmer edit section *** (Ticket.Flight Set end)

                // *** End programmer edit section *** (Ticket.Flight Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Ticket.Passenger CustomAttributes)

        // *** End programmer edit section *** (Ticket.Passenger CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Passenger"})]
        public virtual Universitet.Passenger Passenger
        {
            get
            {
                // *** Start programmer edit section *** (Ticket.Passenger Get start)

                // *** End programmer edit section *** (Ticket.Passenger Get start)
                Universitet.Passenger result = this.fPassenger;
                // *** Start programmer edit section *** (Ticket.Passenger Get end)

                // *** End programmer edit section *** (Ticket.Passenger Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ticket.Passenger Set start)

                // *** End programmer edit section *** (Ticket.Passenger Set start)
                this.fPassenger = value;
                // *** Start programmer edit section *** (Ticket.Passenger Set end)

                // *** End programmer edit section *** (Ticket.Passenger Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "TicketE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TicketE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TicketE", typeof(Universitet.Ticket));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of Ticket.
    /// </summary>
    public class DetailArrayOfTicket : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfTicket(Universitet.Flight fFlight) :
                base(typeof(Ticket), ((ICSSoft.STORMNET.DataObject)(fFlight)))
        {
        }

        /// <summary>
        /// Returns object with type Ticket by index.
        /// </summary>
        public Universitet.Ticket this[int index]
        {
            get
            {
                return ((Universitet.Ticket)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type Ticket.
        /// </summary>
        public virtual void Add(Universitet.Ticket dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
