FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY Universitet/ ./Universitet/

WORKDIR /src/Universitet

RUN dotnet restore "Universitet.sln"
RUN dotnet publish "Universitet.WebAPI/Universitet.WebAPI.csproj" -c Release -f net10.0 --no-restore -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "Universitet.WebAPI.dll"]
