//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Ticket
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Ticket.TicketE.
    /// </summary>
    [DataView(typeof(Ticket), "TicketE")]
    public partial class TicketEDto : TicketDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="TicketEDto"/>.
        /// </summary>
        public TicketEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="TicketEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public TicketEDto(Ticket source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Ticket number.
        /// </summary>
        [PropertyName("TicketNumber")]
        [CaptionProperty("Ticket number")]
        public string TicketNumber { get; set; } = string.Empty;

                /// <summary>
        /// Seat number.
        /// </summary>
        [PropertyName("SeatNumber")]
        [CaptionProperty("Seat number")]
        public string SeatNumber { get; set; } = string.Empty;

        /// <summary>
        /// Price.
        /// </summary>
        [PropertyName("Price")]
        [CaptionProperty("Price")]
        public double Price { get; set; }

        /// <summary>
        /// Passenger.
        /// </summary>
        [PropertyName("Passenger")]
        [CaptionProperty("Passenger")]
        public Guid PassengerId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override TicketEDto FillFromClass(Ticket source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            TicketNumber = source.TicketNumber;
            SeatNumber = source.SeatNumber;
            Price = source.Price;
            PassengerId = PKHelper.GetGuidByObject(source.Passenger).GetValueOrDefault();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Ticket destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.TicketNumber = TicketNumber;
            destination.SeatNumber = SeatNumber;
            destination.Price = Price;

            if (PassengerId != Guid.Empty)
            {
                Passenger passenger = new Passenger();
                passenger.SetExistObjectPrimaryKey(PassengerId);
                destination.Passenger = passenger;
            }
            else
            {
                destination.Passenger = null;
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
