//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Airport
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Universitet;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации AirportL.
    /// </summary>
    public partial class AirportLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AirportLFilterDto"/> class.
        /// </summary>
        public AirportLFilterDto()
        {
            DtoType = typeof(AirportLDto);
        }

        /// <summary>
        /// Code.
        /// </summary>
        public string? Code { get; set; }

        /// <summary>
        /// Code.
        /// </summary>
        public FilterOperation? CodeOp { get; set; }
        /// <summary>
        /// Name.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Name.
        /// </summary>
        public FilterOperation? NameOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (CodeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Airport>(CodeOp.Value, d => d.Code, Code));
            }

            if (NameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Airport>(NameOp.Value, d => d.Name, Name));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
