//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Airport
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Airport.AirportE.
    /// </summary>
    [DataView(typeof(Airport), "AirportE")]
    public partial class AirportEDto : AirportDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AirportEDto"/>.
        /// </summary>
        public AirportEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AirportEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AirportEDto(Airport source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Code.
        /// </summary>
        [PropertyName("Code")]
        [CaptionProperty("Code")]
        public string Code { get; set; } = string.Empty;

                /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Name")]
        public string Name { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AirportEDto FillFromClass(Airport source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Code = source.Code;
            Name = source.Name;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Airport destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Code = Code;
            destination.Name = Name;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
