//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { TicketService } from '@/services/Ticket.service';
import { IBaseTicket } from '@/types/Ticket.types';

const useCreateTicket = <T extends IBaseTicket>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    ticket: T;
    viewName: string;
  };

  const {
    mutate: createTicket,
    mutateAsync: createTicketAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      TicketService.CreateTicket<T>(createRecordArgs.ticket, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'ticket';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createTicket, createTicketAsync, isPending };
};

export default useCreateTicket;
