//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { PassengerService } from '@/services/Passenger.service';
import { IBasePassenger } from '@/types/Passenger.types';

const useCreatePassenger = <T extends IBasePassenger>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    passenger: T;
    viewName: string;
  };

  const {
    mutate: createPassenger,
    mutateAsync: createPassengerAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      PassengerService.CreatePassenger<T>(createRecordArgs.passenger, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'passenger';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createPassenger, createPassengerAsync, isPending };
};

export default useCreatePassenger;
