//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { PassengerService } from '@/services/Passenger.service';

const useDeletePassenger = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deletePassenger,
    mutateAsync: deletePassengerAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => PassengerService.DeletePassenger(id),
    onSuccess: (_, id) => {
      const className = 'passenger';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deletePassenger, deletePassengerAsync, isPending };
};

export default useDeletePassenger;
