//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Airport;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Airport.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class AirportController : ControllerBase
    {
        private readonly IAirportService _airportService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AirportController"/>.
        /// </summary>
        /// <param name="airportService">Сервис для работы с Airport.</param>
        public AirportController(IAirportService airportService)
        {
            _airportService = airportService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Airport в форме AirportEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AirportE")]
        public async Task<ActionResult<GetAllRequestResult<AirportEDto>>> GetAllAirportE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AirportEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Airport по идентификатору в форме AirportEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AirportEDto"/>, если найден.</returns>
        [HttpGet("AirportE/{id:guid}")]
        public async Task<ActionResult<AirportEDto>> GetByIdAirportE(Guid id)
        {
            return await GetById<AirportEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Airport.
        /// </summary>
        /// <returns>Количество Airport.</returns>
        [HttpGet("AirportE/count")]
        public async Task<ActionResult<int>> GetCountAirportE()
        {
            return await GetCount<AirportEDto>();
        }

        /// <summary>
        /// Получить список всех Airport в форме AirportLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AirportL")]
        public async Task<ActionResult<GetAllRequestResult<AirportLDto>>> GetAllAirportL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AirportLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Airport по идентификатору в форме AirportLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AirportLDto"/>, если найден.</returns>
        [HttpGet("AirportL/{id:guid}")]
        public async Task<ActionResult<AirportLDto>> GetByIdAirportL(Guid id)
        {
            return await GetById<AirportLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Airport.
        /// </summary>
        /// <returns>Количество Airport.</returns>
        [HttpGet("AirportL/count")]
        public async Task<ActionResult<int>> GetCountAirportL()
        {
            return await GetCount<AirportLDto>();
        }

        /// <summary>
        /// Удалить Airport.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _airportService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Airport", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Airport для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _airportService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Airport", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Airport.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Airport.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : AirportDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _airportService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _airportService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Airport", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Airport по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Airport в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : AirportDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _airportService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Airport по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Airport.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Airport.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : AirportDtoBase, new()
        {
            try
            {
                int result = await _airportService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Airport", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
