//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.AssosiationClass;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для AssosiationClass.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class AssosiationClassController : ControllerBase
    {
        private readonly IAssosiationClassService _assosiationClassService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AssosiationClassController"/>.
        /// </summary>
        /// <param name="assosiationClassService">Сервис для работы с AssosiationClass.</param>
        public AssosiationClassController(IAssosiationClassService assosiationClassService)
        {
            _assosiationClassService = assosiationClassService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех AssosiationClass в форме AssosiationClassEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AssosiationClassE")]
        public async Task<ActionResult<GetAllRequestResult<AssosiationClassEDto>>> GetAllAssosiationClassE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AssosiationClassEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору в форме AssosiationClassEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AssosiationClassEDto"/>, если найден.</returns>
        [HttpGet("AssosiationClassE/{id:guid}")]
        public async Task<ActionResult<AssosiationClassEDto>> GetByIdAssosiationClassE(Guid id)
        {
            return await GetById<AssosiationClassEDto>(id);
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <returns>Количество AssosiationClass.</returns>
        [HttpGet("AssosiationClassE/count")]
        public async Task<ActionResult<int>> GetCountAssosiationClassE()
        {
            return await GetCount<AssosiationClassEDto>();
        }

        /// <summary>
        /// Получить список всех AssosiationClass в форме AssosiationClassLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AssosiationClassL")]
        public async Task<ActionResult<GetAllRequestResult<AssosiationClassLDto>>> GetAllAssosiationClassL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AssosiationClassLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору в форме AssosiationClassLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AssosiationClassLDto"/>, если найден.</returns>
        [HttpGet("AssosiationClassL/{id:guid}")]
        public async Task<ActionResult<AssosiationClassLDto>> GetByIdAssosiationClassL(Guid id)
        {
            return await GetById<AssosiationClassLDto>(id);
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <returns>Количество AssosiationClass.</returns>
        [HttpGet("AssosiationClassL/count")]
        public async Task<ActionResult<int>> GetCountAssosiationClassL()
        {
            return await GetCount<AssosiationClassLDto>();
        }

        /// <summary>
        /// Удалить AssosiationClass.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _assosiationClassService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все AssosiationClass для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _assosiationClassService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех AssosiationClass.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список AssosiationClass.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : AssosiationClassDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _assosiationClassService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _assosiationClassService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>AssosiationClass в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : AssosiationClassDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _assosiationClassService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AssosiationClass по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество AssosiationClass.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : AssosiationClassDtoBase, new()
        {
            try
            {
                int result = await _assosiationClassService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
