//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Class;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Class.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class ClassController : ControllerBase
    {
        private readonly IClassService _classService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassController"/>.
        /// </summary>
        /// <param name="classService">Сервис для работы с Class.</param>
        public ClassController(IClassService classService)
        {
            _classService = classService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Class в форме ClassEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ClassE")]
        public async Task<ActionResult<GetAllRequestResult<ClassEDto>>> GetAllClassE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<ClassEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Class по идентификатору в форме ClassEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ClassEDto"/>, если найден.</returns>
        [HttpGet("ClassE/{id:guid}")]
        public async Task<ActionResult<ClassEDto>> GetByIdClassE(Guid id)
        {
            return await GetById<ClassEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Class.
        /// </summary>
        /// <returns>Количество Class.</returns>
        [HttpGet("ClassE/count")]
        public async Task<ActionResult<int>> GetCountClassE()
        {
            return await GetCount<ClassEDto>();
        }

        /// <summary>
        /// Получить список всех Class в форме ClassLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ClassL")]
        public async Task<ActionResult<GetAllRequestResult<ClassLDto>>> GetAllClassL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<ClassLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Class по идентификатору в форме ClassLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ClassLDto"/>, если найден.</returns>
        [HttpGet("ClassL/{id:guid}")]
        public async Task<ActionResult<ClassLDto>> GetByIdClassL(Guid id)
        {
            return await GetById<ClassLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Class.
        /// </summary>
        /// <returns>Количество Class.</returns>
        [HttpGet("ClassL/count")]
        public async Task<ActionResult<int>> GetCountClassL()
        {
            return await GetCount<ClassLDto>();
        }

        /// <summary>
        /// Удалить Class.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _classService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Class", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Class для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _classService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Class", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Class.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Class.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : ClassDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _classService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _classService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Class", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Class по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Class в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : ClassDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _classService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Class по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Class.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Class.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : ClassDtoBase, new()
        {
            try
            {
                int result = await _classService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Class", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
