//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Unity;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Airport;
    using Universitet.ApplicationLayer.ExportProviders;

    /// <summary>
    /// Контроллер экспорта списковых форм в Excel.
    /// </summary>
    [ApiController]
    [Route("export")]
    public class ExportController : ControllerBase
    {
        private readonly IUnityContainer _container;

        public ExportController(IUnityContainer container)
        {
            _container = container;
        }

        /// <summary>
        /// Экспорт AirportL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("AirportL")]
        public async Task<IActionResult> ExportAirportL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] AirportLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<AirportDtoBase> provider = _container.Resolve<IExcelExportProvider<AirportDtoBase>>("AirportLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<AirportLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "AirportL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}
