//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Unity;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.ExportProviders;

    /// <summary>
    /// Контроллер экспорта списковых форм в Excel.
    /// </summary>
    [ApiController]
    [Route("export")]
    public class ExportController : ControllerBase
    {
        private readonly IUnityContainer _container;

        public ExportController(IUnityContainer container)
        {
            _container = container;
        }
    }
}
