//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Flight;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Flight.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class FlightController : ControllerBase
    {
        private readonly IFlightService _flightService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FlightController"/>.
        /// </summary>
        /// <param name="flightService">Сервис для работы с Flight.</param>
        public FlightController(IFlightService flightService)
        {
            _flightService = flightService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Flight в форме FlightEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("FlightE")]
        public async Task<ActionResult<GetAllRequestResult<FlightEDto>>> GetAllFlightE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<FlightEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Flight по идентификатору в форме FlightEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="FlightEDto"/>, если найден.</returns>
        [HttpGet("FlightE/{id:guid}")]
        public async Task<ActionResult<FlightEDto>> GetByIdFlightE(Guid id)
        {
            return await GetById<FlightEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Flight.
        /// </summary>
        /// <returns>Количество Flight.</returns>
        [HttpGet("FlightE/count")]
        public async Task<ActionResult<int>> GetCountFlightE()
        {
            return await GetCount<FlightEDto>();
        }

        /// <summary>
        /// Получить список всех Flight в форме FlightLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("FlightL")]
        public async Task<ActionResult<GetAllRequestResult<FlightLDto>>> GetAllFlightL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<FlightLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Flight по идентификатору в форме FlightLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="FlightLDto"/>, если найден.</returns>
        [HttpGet("FlightL/{id:guid}")]
        public async Task<ActionResult<FlightLDto>> GetByIdFlightL(Guid id)
        {
            return await GetById<FlightLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Flight.
        /// </summary>
        /// <returns>Количество Flight.</returns>
        [HttpGet("FlightL/count")]
        public async Task<ActionResult<int>> GetCountFlightL()
        {
            return await GetCount<FlightLDto>();
        }

        /// <summary>
        /// Удалить Flight.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _flightService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Flight", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Flight для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _flightService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Flight", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Flight.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Flight.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : FlightDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _flightService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _flightService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Flight", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Flight по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Flight в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : FlightDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _flightService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Flight по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Flight.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Flight.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : FlightDtoBase, new()
        {
            try
            {
                int result = await _flightService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Flight", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
