//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Helicopter;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Helicopter.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class HelicopterController : ControllerBase
    {
        private readonly IHelicopterService _helicopterService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="HelicopterController"/>.
        /// </summary>
        /// <param name="helicopterService">Сервис для работы с Helicopter.</param>
        public HelicopterController(IHelicopterService helicopterService)
        {
            _helicopterService = helicopterService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Helicopter в форме HelicopterEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("HelicopterE")]
        public async Task<ActionResult<GetAllRequestResult<HelicopterEDto>>> GetAllHelicopterE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<HelicopterEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Helicopter по идентификатору в форме HelicopterEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="HelicopterEDto"/>, если найден.</returns>
        [HttpGet("HelicopterE/{id:guid}")]
        public async Task<ActionResult<HelicopterEDto>> GetByIdHelicopterE(Guid id)
        {
            return await GetById<HelicopterEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Helicopter.
        /// </summary>
        /// <returns>Количество Helicopter.</returns>
        [HttpGet("HelicopterE/count")]
        public async Task<ActionResult<int>> GetCountHelicopterE()
        {
            return await GetCount<HelicopterEDto>();
        }

        /// <summary>
        /// Получить список всех Helicopter в форме HelicopterLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("HelicopterL")]
        public async Task<ActionResult<GetAllRequestResult<HelicopterLDto>>> GetAllHelicopterL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<HelicopterLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Helicopter по идентификатору в форме HelicopterLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="HelicopterLDto"/>, если найден.</returns>
        [HttpGet("HelicopterL/{id:guid}")]
        public async Task<ActionResult<HelicopterLDto>> GetByIdHelicopterL(Guid id)
        {
            return await GetById<HelicopterLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Helicopter.
        /// </summary>
        /// <returns>Количество Helicopter.</returns>
        [HttpGet("HelicopterL/count")]
        public async Task<ActionResult<int>> GetCountHelicopterL()
        {
            return await GetCount<HelicopterLDto>();
        }

        /// <summary>
        /// Удалить Helicopter.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _helicopterService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Helicopter", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Helicopter для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _helicopterService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Helicopter", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Helicopter.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Helicopter.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : HelicopterDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _helicopterService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _helicopterService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Helicopter", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Helicopter по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Helicopter в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : HelicopterDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _helicopterService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Helicopter по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Helicopter.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Helicopter.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : HelicopterDtoBase, new()
        {
            try
            {
                int result = await _helicopterService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Helicopter", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
