//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.InheritanceClass;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для InheritanceClass.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class InheritanceClassController : ControllerBase
    {
        private readonly IInheritanceClassService _inheritanceClassService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="InheritanceClassController"/>.
        /// </summary>
        /// <param name="inheritanceClassService">Сервис для работы с InheritanceClass.</param>
        public InheritanceClassController(IInheritanceClassService inheritanceClassService)
        {
            _inheritanceClassService = inheritanceClassService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех InheritanceClass в форме InheritanceClassEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("InheritanceClassE")]
        public async Task<ActionResult<GetAllRequestResult<InheritanceClassEDto>>> GetAllInheritanceClassE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<InheritanceClassEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить InheritanceClass по идентификатору в форме InheritanceClassEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="InheritanceClassEDto"/>, если найден.</returns>
        [HttpGet("InheritanceClassE/{id:guid}")]
        public async Task<ActionResult<InheritanceClassEDto>> GetByIdInheritanceClassE(Guid id)
        {
            return await GetById<InheritanceClassEDto>(id);
        }

        /// <summary>
        /// Получить общее количество InheritanceClass.
        /// </summary>
        /// <returns>Количество InheritanceClass.</returns>
        [HttpGet("InheritanceClassE/count")]
        public async Task<ActionResult<int>> GetCountInheritanceClassE()
        {
            return await GetCount<InheritanceClassEDto>();
        }

        /// <summary>
        /// Получить список всех InheritanceClass в форме InheritanceClassLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("InheritanceClassL")]
        public async Task<ActionResult<GetAllRequestResult<InheritanceClassLDto>>> GetAllInheritanceClassL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<InheritanceClassLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить InheritanceClass по идентификатору в форме InheritanceClassLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="InheritanceClassLDto"/>, если найден.</returns>
        [HttpGet("InheritanceClassL/{id:guid}")]
        public async Task<ActionResult<InheritanceClassLDto>> GetByIdInheritanceClassL(Guid id)
        {
            return await GetById<InheritanceClassLDto>(id);
        }

        /// <summary>
        /// Получить общее количество InheritanceClass.
        /// </summary>
        /// <returns>Количество InheritanceClass.</returns>
        [HttpGet("InheritanceClassL/count")]
        public async Task<ActionResult<int>> GetCountInheritanceClassL()
        {
            return await GetCount<InheritanceClassLDto>();
        }

        /// <summary>
        /// Удалить InheritanceClass.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _inheritanceClassService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении InheritanceClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все InheritanceClass для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _inheritanceClassService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении InheritanceClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех InheritanceClass.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список InheritanceClass.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : InheritanceClassDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _inheritanceClassService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _inheritanceClassService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении InheritanceClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить InheritanceClass по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>InheritanceClass в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : InheritanceClassDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _inheritanceClassService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении InheritanceClass по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество InheritanceClass.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество InheritanceClass.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : InheritanceClassDtoBase, new()
        {
            try
            {
                int result = await _inheritanceClassService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва InheritanceClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
