//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Universitet;
    using Universitet.ApplicationLayer.DTO;
    using Universitet.ApplicationLayer.DTO.Passenger;
    using Universitet.ApplicationLayer.Helpers;
    using Universitet.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Passenger.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class PassengerController : ControllerBase
    {
        private readonly IPassengerService _passengerService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="PassengerController"/>.
        /// </summary>
        /// <param name="passengerService">Сервис для работы с Passenger.</param>
        public PassengerController(IPassengerService passengerService)
        {
            _passengerService = passengerService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Passenger в форме PassengerEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("PassengerE")]
        public async Task<ActionResult<GetAllRequestResult<PassengerEDto>>> GetAllPassengerE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<PassengerEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Passenger по идентификатору в форме PassengerEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="PassengerEDto"/>, если найден.</returns>
        [HttpGet("PassengerE/{id:guid}")]
        public async Task<ActionResult<PassengerEDto>> GetByIdPassengerE(Guid id)
        {
            return await GetById<PassengerEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Passenger.
        /// </summary>
        /// <returns>Количество Passenger.</returns>
        [HttpGet("PassengerE/count")]
        public async Task<ActionResult<int>> GetCountPassengerE()
        {
            return await GetCount<PassengerEDto>();
        }

        /// <summary>
        /// Получить список всех Passenger в форме PassengerLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("PassengerL")]
        public async Task<ActionResult<GetAllRequestResult<PassengerLDto>>> GetAllPassengerL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<PassengerLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Passenger по идентификатору в форме PassengerLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="PassengerLDto"/>, если найден.</returns>
        [HttpGet("PassengerL/{id:guid}")]
        public async Task<ActionResult<PassengerLDto>> GetByIdPassengerL(Guid id)
        {
            return await GetById<PassengerLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Passenger.
        /// </summary>
        /// <returns>Количество Passenger.</returns>
        [HttpGet("PassengerL/count")]
        public async Task<ActionResult<int>> GetCountPassengerL()
        {
            return await GetCount<PassengerLDto>();
        }

        /// <summary>
        /// Удалить Passenger.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _passengerService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Passenger", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Passenger для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _passengerService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Passenger", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Passenger.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Passenger.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : PassengerDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _passengerService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _passengerService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Passenger", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Passenger по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Passenger в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : PassengerDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _passengerService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Passenger по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Passenger.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Passenger.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : PassengerDtoBase, new()
        {
            try
            {
                int result = await _passengerService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Passenger", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
