//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AirplaneService } from '@/services/Airplane.service';

const useDeleteAirplane = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAirplane,
    mutateAsync: deleteAirplaneAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => AirplaneService.DeleteAirplane(id),
    onSuccess: (_, id) => {
      const className = 'airplane';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteAirplane, deleteAirplaneAsync, isPending };
};

export default useDeleteAirplane;
