//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AirplaneService } from '@/services/Airplane.service';

const useDeleteAllAirplane = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllAirplane,
    mutateAsync: deleteAllAirplaneAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => AirplaneService.DeleteAllAirplane(ids),
    onSuccess: (_, ids) => {
      const className = 'airplane';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllAirplane, deleteAllAirplaneAsync, isPending };
};

export default useDeleteAllAirplane;
