//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useEffect } from 'react';
import { isAxiosError } from 'axios';
import { useQuery } from '@tanstack/react-query';

import { AirplaneService } from '@/services/Airplane.service';
import type { IBaseAirplane } from '@/types/Airplane.types';
import type { GetRequestOptions } from '@/types/helpers/GetRequestOptions';

const useGetAirplane = <T extends IBaseAirplane>({ id, viewName, enabled = true, onNotFound }: GetRequestOptions) => {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['airplane', id],
    retry: false,
    enabled: enabled,
    queryFn: async (): Promise<T> => {
      const response = await AirplaneService.GetAirplane(id, viewName);
      return response.data;
    },
  });

  useEffect(() => {
    if (isError && isAxiosError(error)) {
      if (typeof onNotFound === 'function' && error.response?.status === 404) {
        onNotFound();
      }
    }
  }, [error, isError, onNotFound]);

  return {
    data,
    isLoading,
    isError,
  };
};

export default useGetAirplane;
