//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAircraft } from '@/types/Aircraft.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AircraftService = {
  async GetAllAircraft(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/aircraft/${viewName}${queryStr}`);
  },

  async GetAircraft(id: string, viewName: string) {
    return await axiosInstance.get(`/aircraft/${viewName}/${id}`);
  },

  async CreateAircraft<T extends IBaseAircraft>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/aircraft/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAircraft<T extends IBaseAircraft>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/aircraft/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAircraft(id: string) {
    return await axiosInstance.delete(`/aircraft/${id}`);
  },

  async DeleteAllAircraft(ids: string[]) {
    return await axiosInstance.post(`/aircraft/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/aircraft/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
