//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAirport } from '@/types/Airport.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AirportService = {
  async GetAllAirport(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/airport/${viewName}${queryStr}`);
  },

  async GetAirport(id: string, viewName: string) {
    return await axiosInstance.get(`/airport/${viewName}/${id}`);
  },

  async CreateAirport<T extends IBaseAirport>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/airport/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAirport<T extends IBaseAirport>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/airport/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAirport(id: string) {
    return await axiosInstance.delete(`/airport/${id}`);
  },

  async DeleteAllAirport(ids: string[]) {
    return await axiosInstance.post(`/airport/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/airport/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
