//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAirplane } from '@/types/Airplane.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AirplaneService = {
  async GetAllAirplane(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/airplane/${viewName}${queryStr}`);
  },

  async GetAirplane(id: string, viewName: string) {
    return await axiosInstance.get(`/airplane/${viewName}/${id}`);
  },

  async CreateAirplane<T extends IBaseAirplane>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/airplane/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAirplane<T extends IBaseAirplane>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/airplane/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAirplane(id: string) {
    return await axiosInstance.delete(`/airplane/${id}`);
  },

  async DeleteAllAirplane(ids: string[]) {
    return await axiosInstance.post(`/airplane/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/airplane/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
