//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAssosiationClass } from '@/types/AssosiationClass.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AssosiationClassService = {
  async GetAllAssosiationClass(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/assosiationclass/${viewName}${queryStr}`);
  },

  async GetAssosiationClass(id: string, viewName: string) {
    return await axiosInstance.get(`/assosiationclass/${viewName}/${id}`);
  },

  async CreateAssosiationClass<T extends IBaseAssosiationClass>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/assosiationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAssosiationClass<T extends IBaseAssosiationClass>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/assosiationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAssosiationClass(id: string) {
    return await axiosInstance.delete(`/assosiationclass/${id}`);
  },

  async DeleteAllAssosiationClass(ids: string[]) {
    return await axiosInstance.post(`/assosiationclass/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/assosiationclass/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
