//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseFlight } from '@/types/Flight.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const FlightService = {
  async GetAllFlight(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/flight/${viewName}${queryStr}`);
  },

  async GetFlight(id: string, viewName: string) {
    return await axiosInstance.get(`/flight/${viewName}/${id}`);
  },

  async CreateFlight<T extends IBaseFlight>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/flight/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateFlight<T extends IBaseFlight>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/flight/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteFlight(id: string) {
    return await axiosInstance.delete(`/flight/${id}`);
  },

  async DeleteAllFlight(ids: string[]) {
    return await axiosInstance.post(`/flight/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/flight/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
