//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseHelicopter } from '@/types/Helicopter.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const HelicopterService = {
  async GetAllHelicopter(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/helicopter/${viewName}${queryStr}`);
  },

  async GetHelicopter(id: string, viewName: string) {
    return await axiosInstance.get(`/helicopter/${viewName}/${id}`);
  },

  async CreateHelicopter<T extends IBaseHelicopter>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/helicopter/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateHelicopter<T extends IBaseHelicopter>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/helicopter/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteHelicopter(id: string) {
    return await axiosInstance.delete(`/helicopter/${id}`);
  },

  async DeleteAllHelicopter(ids: string[]) {
    return await axiosInstance.post(`/helicopter/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/helicopter/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
