//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseInheritanceClass } from '@/types/InheritanceClass.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const InheritanceClassService = {
  async GetAllInheritanceClass(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/inheritanceclass/${viewName}${queryStr}`);
  },

  async GetInheritanceClass(id: string, viewName: string) {
    return await axiosInstance.get(`/inheritanceclass/${viewName}/${id}`);
  },

  async CreateInheritanceClass<T extends IBaseInheritanceClass>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/inheritanceclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateInheritanceClass<T extends IBaseInheritanceClass>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/inheritanceclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteInheritanceClass(id: string) {
    return await axiosInstance.delete(`/inheritanceclass/${id}`);
  },

  async DeleteAllInheritanceClass(ids: string[]) {
    return await axiosInstance.post(`/inheritanceclass/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/inheritanceclass/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
