//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBasePassenger } from '@/types/Passenger.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const PassengerService = {
  async GetAllPassenger(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/passenger/${viewName}${queryStr}`);
  },

  async GetPassenger(id: string, viewName: string) {
    return await axiosInstance.get(`/passenger/${viewName}/${id}`);
  },

  async CreatePassenger<T extends IBasePassenger>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/passenger/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdatePassenger<T extends IBasePassenger>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/passenger/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeletePassenger(id: string) {
    return await axiosInstance.delete(`/passenger/${id}`);
  },

  async DeleteAllPassenger(ids: string[]) {
    return await axiosInstance.post(`/passenger/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/passenger/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
