//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseTicket } from '@/types/Ticket.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const TicketService = {
  async GetAllTicket(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/ticket/${viewName}${queryStr}`);
  },

  async GetTicket(id: string, viewName: string) {
    return await axiosInstance.get(`/ticket/${viewName}/${id}`);
  },

  async CreateTicket<T extends IBaseTicket>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/ticket/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateTicket<T extends IBaseTicket>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/ticket/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteTicket(id: string) {
    return await axiosInstance.delete(`/ticket/${id}`);
  },

  async DeleteAllTicket(ids: string[]) {
    return await axiosInstance.post(`/ticket/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/ticket/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
