//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export enum tView {
  AircraftE = 'AircraftE',
  AircraftL = 'AircraftL',
  AirplaneE = 'AirplaneE',
  AirplaneL = 'AirplaneL',
  AirportE = 'AirportE',
  AirportL = 'AirportL',
  FlightE = 'FlightE',
  FlightL = 'FlightL',
  HelicopterE = 'HelicopterE',
  HelicopterL = 'HelicopterL',
  PassengerE = 'PassengerE',
  PassengerL = 'PassengerL',
  TicketE = 'TicketE',
  // *** Start programmer edit section *** (Additional views)

  // *** End programmer edit section *** (Additional views)
}
