//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Class
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Class.ClassL.
    /// </summary>
    [DataView(typeof(Class), "ClassL")]
    public partial class ClassLDto : ClassDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassLDto"/>.
        /// </summary>
        public ClassLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ClassLDto(Class source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Address.
        /// </summary>
        [PropertyName("Address")]
        [CaptionProperty("Address")]
        public string Address { get; set; } = string.Empty;

                /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Name")]
        public string Name { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ClassLDto FillFromClass(Class source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Address = source.Address;
            Name = source.Name;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Class destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Address = Address;
            destination.Name = Name;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
