//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.InheritanceClass
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления InheritanceClass.InheritanceClassE.
    /// </summary>
    [DataView(typeof(InheritanceClass), "InheritanceClassE")]
    public partial class InheritanceClassEDto : InheritanceClassDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="InheritanceClassEDto"/>.
        /// </summary>
        public InheritanceClassEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="InheritanceClassEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public InheritanceClassEDto(InheritanceClass source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("")]
        public string Name { get; set; } = string.Empty;

                /// <summary>
        /// Address.
        /// </summary>
        [PropertyName("Address")]
        [CaptionProperty("")]
        public string Address { get; set; } = string.Empty;

                /// <summary>
        /// Inheritance.
        /// </summary>
        [PropertyName("Inheritance")]
        [CaptionProperty("")]
        public string Inheritance { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override InheritanceClassEDto FillFromClass(InheritanceClass source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            Address = source.Address;
            Inheritance = source.Inheritance;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(InheritanceClass destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.Address = Address;
            destination.Inheritance = Inheritance;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
