//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Airplane
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Airplane.AirplaneL.
    /// </summary>
    [DataView(typeof(Airplane), "AirplaneL")]
    public partial class AirplaneLDto : AirplaneDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AirplaneLDto"/>.
        /// </summary>
        public AirplaneLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AirplaneLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AirplaneLDto(Airplane source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Wingspan.
        /// </summary>
        [PropertyName("Wingspan")]
        [CaptionProperty("Wingspan")]
        public double Wingspan { get; set; }

        /// <summary>
        /// Engine count.
        /// </summary>
        [PropertyName("EngineCount")]
        [CaptionProperty("Engine count")]
        public int EngineCount { get; set; }

                /// <summary>
        /// Registration number.
        /// </summary>
        [PropertyName("RegistrationNumber")]
        [CaptionProperty("Registration number")]
        public string RegistrationNumber { get; set; } = string.Empty;

                /// <summary>
        /// Model.
        /// </summary>
        [PropertyName("Model")]
        [CaptionProperty("Model")]
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Capacity.
        /// </summary>
        [PropertyName("Capacity")]
        [CaptionProperty("Capacity")]
        public int Capacity { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AirplaneLDto FillFromClass(Airplane source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Wingspan = source.Wingspan;
            EngineCount = source.EngineCount;
            RegistrationNumber = source.RegistrationNumber;
            Model = source.Model;
            Capacity = source.Capacity;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Airplane destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Wingspan = Wingspan;
            destination.EngineCount = EngineCount;
            destination.RegistrationNumber = RegistrationNumber;
            destination.Model = Model;
            destination.Capacity = Capacity;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
