//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Flight
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Flight.FlightE.
    /// </summary>
    [DataView(typeof(Flight), "FlightE")]
    public partial class FlightEDto : FlightDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FlightEDto"/>.
        /// </summary>
        public FlightEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FlightEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public FlightEDto(Flight source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Flight number.
        /// </summary>
        [PropertyName("FlightNumber")]
        [CaptionProperty("Flight number")]
        public string FlightNumber { get; set; } = string.Empty;

        /// <summary>
        /// Departure time.
        /// </summary>
        [PropertyName("DepartureTime")]
        [CaptionProperty("Departure time")]
        public DateTime DepartureTime { get; set; }

        /// <summary>
        /// Arrival time.
        /// </summary>
        [PropertyName("ArrivalTime")]
        [CaptionProperty("Arrival time")]
        public DateTime ArrivalTime { get; set; }

        /// <summary>
        /// Status.
        /// </summary>
        [PropertyName("Status")]
        [CaptionProperty("Status")]
        public tFlightStatus Status { get; set; }

        /// <summary>
        /// Aircraft.
        /// </summary>
        [PropertyName("Aircraft")]
        [CaptionProperty("Aircraft")]
        public Guid AircraftId { get; set; }

        /// <summary>
        /// DepartureAirport.
        /// </summary>
        [PropertyName("DepartureAirport")]
        [CaptionProperty("DepartureAirport")]
        public Guid DepartureAirportId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Ticket.
        /// </summary>
        public List<DTO.Ticket.TicketEDto> Ticket { get; set; } = new List<DTO.Ticket.TicketEDto>();

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override FlightEDto FillFromClass(Flight source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            FlightNumber = source.FlightNumber;
            DepartureTime = source.DepartureTime.ToUniversalTime();
            ArrivalTime = source.ArrivalTime.ToUniversalTime();
            Status = source.Status;
            AircraftId = PKHelper.GetGuidByObject(source.Aircraft).GetValueOrDefault();
            DepartureAirportId = PKHelper.GetGuidByObject(source.DepartureAirport).GetValueOrDefault();
            Ticket = source.Ticket.GetAllObjects().Cast<Ticket>().Select(d => new DTO.Ticket.TicketEDto(d)).ToList();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Flight destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.FlightNumber = FlightNumber;
            destination.DepartureTime = DepartureTime.ToUniversalTime();
            destination.ArrivalTime = ArrivalTime.ToUniversalTime();
            destination.Status = Status;

            if (AircraftId != Guid.Empty)
            {
                Aircraft aircraft = new Aircraft();
                aircraft.SetExistObjectPrimaryKey(AircraftId);
                destination.Aircraft = aircraft;
            }
            else
            {
                destination.Aircraft = null;
            }

            if (DepartureAirportId != Guid.Empty)
            {
                Airport departureAirport = new Airport();
                departureAirport.SetExistObjectPrimaryKey(DepartureAirportId);
                destination.DepartureAirport = departureAirport;
            }
            else
            {
                destination.DepartureAirport = null;
            }

            DataObject[] detailsTicket = destination.Ticket.GetAllObjects();
            foreach (DTO.Ticket.TicketEDto detailDto in Ticket)
            {
                DataObject? detail = detailsTicket.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new Ticket() { Flight = destination };
                    destination.Ticket.AddObject(detail);
                }

                detailDto.UpdateFromDto((Ticket)detail);
            }

            foreach (Ticket detail in detailsTicket)
            {
                if (!Ticket.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
