//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Flight
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Flight.FlightL.
    /// </summary>
    [DataView(typeof(Flight), "FlightL")]
    public partial class FlightLDto : FlightDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FlightLDto"/>.
        /// </summary>
        public FlightLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FlightLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public FlightLDto(Flight source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Flight number.
        /// </summary>
        [PropertyName("FlightNumber")]
        [CaptionProperty("Flight number")]
        public string FlightNumber { get; set; } = string.Empty;

        /// <summary>
        /// Departure time.
        /// </summary>
        [PropertyName("DepartureTime")]
        [CaptionProperty("Departure time")]
        public DateTime DepartureTime { get; set; }

        /// <summary>
        /// Arrival time.
        /// </summary>
        [PropertyName("ArrivalTime")]
        [CaptionProperty("Arrival time")]
        public DateTime ArrivalTime { get; set; }

        /// <summary>
        /// Status.
        /// </summary>
        [PropertyName("Status")]
        [CaptionProperty("Status")]
        public tFlightStatus Status { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override FlightLDto FillFromClass(Flight source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            FlightNumber = source.FlightNumber;
            DepartureTime = source.DepartureTime.ToUniversalTime();
            ArrivalTime = source.ArrivalTime.ToUniversalTime();
            Status = source.Status;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Flight destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.FlightNumber = FlightNumber;
            destination.DepartureTime = DepartureTime.ToUniversalTime();
            destination.ArrivalTime = ArrivalTime.ToUniversalTime();
            destination.Status = Status;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
