//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Flight
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Universitet;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации FlightL.
    /// </summary>
    public partial class FlightLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightLFilterDto"/> class.
        /// </summary>
        public FlightLFilterDto()
        {
            DtoType = typeof(FlightLDto);
        }

        /// <summary>
        /// Flight number.
        /// </summary>
        public string? FlightNumber { get; set; }

        /// <summary>
        /// Flight number.
        /// </summary>
        public FilterOperation? FlightNumberOp { get; set; }
        /// <summary>
        /// Departure time.
        /// </summary>
        public DateTime? DepartureTime { get; set; }

        /// <summary>
        /// Departure time.
        /// </summary>
        public FilterOperation? DepartureTimeOp { get; set; }
        /// <summary>
        /// Arrival time.
        /// </summary>
        public DateTime? ArrivalTime { get; set; }

        /// <summary>
        /// Arrival time.
        /// </summary>
        public FilterOperation? ArrivalTimeOp { get; set; }
        /// <summary>
        /// Status.
        /// </summary>
        public tFlightStatus? Status { get; set; }

        /// <summary>
        /// Status.
        /// </summary>
        public FilterOperation? StatusOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (FlightNumberOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Flight>(FlightNumberOp.Value, d => d.FlightNumber, FlightNumber));
            }

            if (DepartureTimeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Flight>(DepartureTimeOp.Value, d => d.DepartureTime, DepartureTime));
            }

            if (ArrivalTimeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Flight>(ArrivalTimeOp.Value, d => d.ArrivalTime, ArrivalTime));
            }

            if (StatusOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Flight>(StatusOp.Value, d => d.Status, Status));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
