




CREATE TABLE Flight (
 primaryKey UUID NOT NULL,
 ArrivalTime TIMESTAMP(3) NULL,
 DepartureTime TIMESTAMP(3) NULL,
 FlightNumber VARCHAR(255) NULL,
 Status VARCHAR(9) NULL,
 Aircraft_m0 UUID NULL,
 Aircraft_m1 UUID NULL,
 DepartureAirport UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Airplane (
 primaryKey UUID NOT NULL,
 EngineCount INT NULL,
 Wingspan DOUBLE PRECISION NULL,
 Capacity INT NULL,
 Model VARCHAR(255) NULL,
 RegistrationNumber VARCHAR(255) NULL,
 ffff INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Helicopter (
 primaryKey UUID NOT NULL,
 MaxAltitude DOUBLE PRECISION NULL,
 RotorDiameter DOUBLE PRECISION NULL,
 Capacity INT NULL,
 Model VARCHAR(255) NULL,
 RegistrationNumber VARCHAR(255) NULL,
 ffff INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Passenger (
 primaryKey UUID NOT NULL,
 FirstName VARCHAR(255) NULL,
 LastName VARCHAR(255) NULL,
 PassportNumber VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Airport (
 primaryKey UUID NOT NULL,
 Code VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Ticket (
 primaryKey UUID NOT NULL,
 Price DOUBLE PRECISION NULL,
 SeatNumber VARCHAR(255) NULL,
 TicketNumber VARCHAR(255) NULL,
 Passenger UUID NOT NULL,
 Flight UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Flight ADD CONSTRAINT FK4d520ab18de9522e547773abee855a7fd41eae90 FOREIGN KEY (Aircraft_m0) REFERENCES Airplane; 
CREATE INDEX Index4d520ab18de9522e547773abee855a7fd41eae90 on Flight (Aircraft_m0); 

 ALTER TABLE Flight ADD CONSTRAINT FK5352f21537c6713c5fa590a541ddc312c79b7952 FOREIGN KEY (Aircraft_m1) REFERENCES Helicopter; 
CREATE INDEX Index5352f21537c6713c5fa590a541ddc312c79b7952 on Flight (Aircraft_m1); 

 ALTER TABLE Flight ADD CONSTRAINT FK8cef17ef4f4a7740e1bba07927c79eeea9e4b212 FOREIGN KEY (DepartureAirport) REFERENCES Airport; 
CREATE INDEX Index8cef17ef4f4a7740e1bba07927c79eeea9e4b212 on Flight (DepartureAirport); 

 ALTER TABLE Ticket ADD CONSTRAINT FK1c2f33828a87f07e8ce79237270776c557052f52 FOREIGN KEY (Passenger) REFERENCES Passenger; 
CREATE INDEX Index1c2f33828a87f07e8ce79237270776c557052f52 on Ticket (Passenger); 

 ALTER TABLE Ticket ADD CONSTRAINT FK9bedc4913b5eee7f1e622f5555ceb2ec9ee72c22 FOREIGN KEY (Flight) REFERENCES Flight; 
CREATE INDEX Index9bedc4913b5eee7f1e622f5555ceb2ec9ee72c22 on Ticket (Flight); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

