//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AssosiationClassService } from '@/services/AssosiationClass.service';
import { IBaseAssosiationClass } from '@/types/AssosiationClass.types';

const useCreateAssosiationClass = <T extends IBaseAssosiationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    assosiationClass: T;
    viewName: string;
  };

  const {
    mutate: createAssosiationClass,
    mutateAsync: createAssosiationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      AssosiationClassService.CreateAssosiationClass<T>(createRecordArgs.assosiationClass, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'assosiationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createAssosiationClass, createAssosiationClassAsync, isPending };
};

export default useCreateAssosiationClass;
