//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AssosiationClassService } from '@/services/AssosiationClass.service';
import { IBaseAssosiationClass } from '@/types/AssosiationClass.types';

const useUpdateAssosiationClass = <T extends IBaseAssosiationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    assosiationClass: T;
    viewName: string;
  };

  const {
    mutate: updateAssosiationClass,
    mutateAsync: updateAssosiationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      AssosiationClassService.UpdateAssosiationClass<T>(updateRecordArgs.assosiationClass, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'assosiationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateAssosiationClass, updateAssosiationClassAsync, isPending };
};

export default useUpdateAssosiationClass;
