//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AircraftService } from '@/services/Aircraft.service';

const useDeleteAircraft = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAircraft,
    mutateAsync: deleteAircraftAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => AircraftService.DeleteAircraft(id),
    onSuccess: (_, id) => {
      const className = 'aircraft';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteAircraft, deleteAircraftAsync, isPending };
};

export default useDeleteAircraft;
