//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AircraftService } from '@/services/Aircraft.service';
import { IBaseAircraft } from '@/types/Aircraft.types';

const useUpdateAircraft = <T extends IBaseAircraft>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    aircraft: T;
    viewName: string;
  };

  const {
    mutate: updateAircraft,
    mutateAsync: updateAircraftAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      AircraftService.UpdateAircraft<T>(updateRecordArgs.aircraft, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'aircraft';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateAircraft, updateAircraftAsync, isPending };
};

export default useUpdateAircraft;
