//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Aircraft
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Universitet;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации AircraftL.
    /// </summary>
    public partial class AircraftLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AircraftLFilterDto"/> class.
        /// </summary>
        public AircraftLFilterDto()
        {
            DtoType = typeof(AircraftLDto);
        }

        /// <summary>
        /// Registration number.
        /// </summary>
        public string? RegistrationNumber { get; set; }

        /// <summary>
        /// Registration number.
        /// </summary>
        public FilterOperation? RegistrationNumberOp { get; set; }
        /// <summary>
        /// Model.
        /// </summary>
        public string? Model { get; set; }

        /// <summary>
        /// Model.
        /// </summary>
        public FilterOperation? ModelOp { get; set; }
        /// <summary>
        /// Capacity.
        /// </summary>
        public int? Capacity { get; set; }

        /// <summary>
        /// Capacity.
        /// </summary>
        public FilterOperation? CapacityOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (RegistrationNumberOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Aircraft>(RegistrationNumberOp.Value, d => d.RegistrationNumber, RegistrationNumber));
            }

            if (ModelOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Aircraft>(ModelOp.Value, d => d.Model, Model));
            }

            if (CapacityOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Aircraft>(CapacityOp.Value, d => d.Capacity, Capacity));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
