//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Universitet.ApplicationLayer.DTO.Aircraft
{
    using System;
    using ICSSoft.STORMNET;
    using Universitet;
    using Universitet.ApplicationLayer;
    using Universitet.ApplicationLayer.Attributes;
    using Universitet.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Aircraft.AircraftL.
    /// </summary>
    [DataView(typeof(Aircraft), "AircraftL")]
    public partial class AircraftLDto : AircraftDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AircraftLDto"/>.
        /// </summary>
        public AircraftLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AircraftLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AircraftLDto(Aircraft source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Registration number.
        /// </summary>
        [PropertyName("RegistrationNumber")]
        [CaptionProperty("Registration number")]
        public string RegistrationNumber { get; set; } = string.Empty;

                /// <summary>
        /// Model.
        /// </summary>
        [PropertyName("Model")]
        [CaptionProperty("Model")]
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Capacity.
        /// </summary>
        [PropertyName("Capacity")]
        [CaptionProperty("Capacity")]
        public int Capacity { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AircraftLDto FillFromClass(Aircraft source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            RegistrationNumber = source.RegistrationNumber;
            Model = source.Model;
            Capacity = source.Capacity;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Aircraft destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.RegistrationNumber = RegistrationNumber;
            destination.Model = Model;
            destination.Capacity = Capacity;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
